#version: "6"
#services:
#  nginx:
#    image: nginx
#    restart: always # because it is routing traffic to our entire app
#    ports:
#      - '80:80'
#    volumes:
#      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
#
#  front:
#    volumes:
#      - ../womans_club_front:/usr/src/app
#      - /app/node_modules
#      - /app/.next
#    environment:
#      NODE_ENV: production
#    build:
#      dockerfile: Dockerfile
#      context: '../womans_club_front'
#    ports:
#      - '3000:3000'
#    restart: always
#    container_name: front
#  admin:
#    build:
#      dockerfile: Dockerfile
#      context: '../womans_club_admin'
#    volumes:
#      - /usr/src/app/node_modules
#      - ../womans_club_admin:/usr/src/app
#    ports:
#      - '8080:8080'
#    restart: always
#    container_name: admin
#    environment:
#      - NODE_ENV=production
#  api:
#    build:
#      dockerfile: Dockerfile
#      context: './'
#    ports:
#      - '4444:4444'
#    volumes:
#      - /app/node_modules
#      - ./:/app
#    container_name: api
#  mongo:
#    image: 'mongo'
#    container_name: 'mongo-db'
#    ports:
#      - '27017:27017'
#    volumes:
#      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#      - ./db/mongo-volume:/data/db
##    env_file:
##      - ./env/mongo.env


version: "6"
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo-db'
    ports:
      - '27017:27017'
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
